_wandb:
    value:
        cli_version: 0.23.0
        e:
            et5mqklo564lvwbsuoovzu8cbv80v0ug:
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "500104687616"
                        used: "497823039488"
                email: alex.mario1404@gmail.com
                executable: E:\Object Detection\Bottle Cap\Bottlecaps_detection\.venv\Scripts\python.exe
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-66f9d8c9-d7bb-6f2f-ee49-3e815950d7f3
                host: AOC
                memory:
                    total: "34180603904"
                os: Windows-10-10.0.26200-SP0
                program: <python with no main file>
                python: CPython 3.11.5
                root: E:\Object Detection\Bottle Cap\Bottlecaps_detection
                startedAt: "2025-11-16T10:01:18.566351Z"
                writerId: et5mqklo564lvwbsuoovzu8cbv80v0ug
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.11.5
            "5": 0.23.0
            "8":
                - 1
                - 3
            "12": 0.23.0
            "13": windows-amd64
        visualize:
            curves/F1-Confidence(B):
                panel_config:
                    fieldSettings:
                        class: class
                        x: x
                        "y": "y"
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: F1-Confidence(B)
                        x-axis-title: Confidence
                        y-axis-title: F1
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: curves/F1-Confidence(B)_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            curves/Precision-Confidence(B):
                panel_config:
                    fieldSettings:
                        class: class
                        x: x
                        "y": "y"
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Precision-Confidence(B)
                        x-axis-title: Confidence
                        y-axis-title: Precision
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: curves/Precision-Confidence(B)_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            curves/Precision-Recall(B):
                panel_config:
                    fieldSettings:
                        class: class
                        x: x
                        "y": "y"
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Precision-Recall(B)
                        x-axis-title: Recall
                        y-axis-title: Precision
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: curves/Precision-Recall(B)_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            curves/Recall-Confidence(B):
                panel_config:
                    fieldSettings:
                        class: class
                        x: x
                        "y": "y"
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Recall-Confidence(B)
                        x-axis-title: Confidence
                        y-axis-title: Recall
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: curves/Recall-Confidence(B)_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
agnostic_nms:
    value: false
amp:
    value: true
augment:
    value: false
auto_augment:
    value: randaugment
batch:
    value: 16
bgr:
    value: 0
box:
    value: 7.5
cache:
    value: false
cfg:
    value: null
classes:
    value: null
close_mosaic:
    value: 10
cls:
    value: 0.5
compile:
    value: false
conf:
    value: null
copy_paste:
    value: 0
copy_paste_mode:
    value: flip
cos_lr:
    value: false
cutmix:
    value: 0
data:
    value: data.yaml
degrees:
    value: 0
deterministic:
    value: true
device:
    value: cpu
dfl:
    value: 1.5
dnn:
    value: false
dropout:
    value: 0.15
dynamic:
    value: false
embed:
    value: null
epochs:
    value: 100
erasing:
    value: 0.4
exist_ok:
    value: false
fliplr:
    value: 0.5
flipud:
    value: 0
format:
    value: torchscript
fraction:
    value: 1
freeze:
    value: null
half:
    value: false
hsv_h:
    value: 0.015
hsv_s:
    value: 0.7
hsv_v:
    value: 0.4
imgsz:
    value: 640
int8:
    value: false
iou:
    value: 0.7
keras:
    value: false
kobj:
    value: 1
line_width:
    value: null
lr0:
    value: 0.0001
lrf:
    value: 0.01
mask_ratio:
    value: 4
max_det:
    value: 300
mixup:
    value: 0
mode:
    value: train
model:
    value: yolov8n.pt
momentum:
    value: 0.937
mosaic:
    value: 1
multi_scale:
    value: false
name:
    value: run3
nbs:
    value: 64
nms:
    value: false
opset:
    value: null
optimize:
    value: false
optimizer:
    value: Adam
overlap_mask:
    value: true
patience:
    value: 10
perspective:
    value: 0
plots:
    value: true
pose:
    value: 12
pretrained:
    value: true
profile:
    value: false
project:
    value: Bottle-Caps-Detection
rect:
    value: false
resume:
    value: false
retina_masks:
    value: false
save:
    value: true
save_conf:
    value: false
save_crop:
    value: false
save_dir:
    value: E:\Object Detection\Bottle Cap\Bottlecaps_detection\Bottle-Caps-Detection\run3
save_frames:
    value: false
save_json:
    value: false
save_period:
    value: -1
save_txt:
    value: false
scale:
    value: 0.5
seed:
    value: 0
shear:
    value: 0
show:
    value: false
show_boxes:
    value: true
show_conf:
    value: true
show_labels:
    value: true
simplify:
    value: true
single_cls:
    value: false
source:
    value: null
split:
    value: val
stream_buffer:
    value: false
task:
    value: detect
time:
    value: null
tracker:
    value: botsort.yaml
translate:
    value: 0.1
val:
    value: true
verbose:
    value: true
vid_stride:
    value: 1
visualize:
    value: false
warmup_bias_lr:
    value: 0.1
warmup_epochs:
    value: 3
warmup_momentum:
    value: 0.8
weight_decay:
    value: 0.0005
workers:
    value: 0
workspace:
    value: null
