dataset:
  data_yaml: "data.yaml"
  train_path: "train"
  val_path: "valid"
  test_path: "test"

model:
  pretrained: "yolov8n.pt"
  epochs: 100
  imgsz: 640
  lr0: 0.0001
  optimizer: "Adam"
  dropout: 0.15
  patience: 10
  project: "Bottle-Caps-Detection"
  run_name: "run5"

inference:
  conf_threshold: 0.25
  iou_threshold: 0.45
  image_size: 640

wandb:
  project: "Bottle-Caps-Detection"
