name: Python CI

on: [push, pull_request]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # -----------------------------------------------------------------
      # STEP CACHING:
      # -----------------------------------------------------------------
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip  # Lokasi cache pip di server Linux
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      # -----------------------------------------------------------------

      - name: Install Dependencies (Akan cepat setelah run pertama)
        run: |
          pip install --upgrade pip
          pip install .
          pip install pytest pylint black isort # Pastikan semua alat terinstal

      # LINTERS
      - name: Check formatting with Black
        run: black --check .

      - name: Check imports with isort
        run: isort --check .

      - name: Lint with Pylint
        run: pylint src/bsort

      # TEST & BUILD
      - name: Test with Pytest
        run: pytest tests/

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag bsort-image:latest